version: '3'

services:
  gitlab:
    container_name: gitlab-test-client-ft-gitlab
    image: ${DOCKER_REGISTRY}/gitlab/gitlab-ce:16.2.4-ce.0
    depends_on:
      - gitlab-db
    ports:
      - "8990:8990"
    volumes:
      - ./gitlab.rb:/etc/gitlab/gitlab.rb

  gitlab-db:
    container_name: gitlab-test-client-ft-gitlab-db
    image: ${DOCKER_REGISTRY}/postgres:13-alpine
    environment:
      POSTGRES_USER: gitlab
      POSTGRES_PASSWORD: gitlab
      POSTGRES_DB: gitlab
