version: '3'

services:
  teamcity-2022:
    image: ${DOCKER_REGISTRY}/octopusden/external-clients/teamcity-server:${TEAMCITY_2022_IMAGE_TAG}
    ports:
      - "8111:8111"
    healthcheck:
      test: curl -u admin:admin -f teamcity-2022:8111/app/rest/server >/dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 5

  teamcity-2025:
    image: ${DOCKER_REGISTRY}/octopusden/external-clients/teamcity-server:${TEAMCITY_2025_IMAGE_TAG}
    ports:
      - "8112:8111"
    healthcheck:
      test: curl -u admin:admin -f teamcity-2025:8111/app/rest/server >/dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 5