version: '3'

services:
  teamcity-2025:
    image: ${DOCKER_REGISTRY}/jetbrains/teamcity-server:2025.03.3
    ports:
      - "8112:8111"
    volumes:
      - ./../build/teamcity-server-2025/datadir:/data/teamcity_server/datadir
      - ./../build/teamcity-server-2025/logs:/opt/teamcity/logs
    healthcheck:
      test: curl -u admin:admin -f teamcity-2025:8111/app/rest/server >/dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 50