name: Check

on:
  push:
  pull_request:
    types: [ opened, reopened ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Prod
    steps:
      - uses: actions/checkout@v3
        name: Checkout(switching to commit)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'gradle'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: tag_version
        with:
          initial_version: v0.0.0
      - uses: actions-ecosystem/action-bump-semver@v1
        id: bump_semver
        with:
          current_version: ${{ steps.tag_version.outputs.tag }}
          level: patch
      - uses: octopusden/octopus-base/.github/actions/get-version@main
        name: Get version
        id: version
        with:
          tag-value: ${{ steps.bump_semver.outputs.new_version }}
          exit-if-empty: true
      - name: Build
        run: ./gradlew build -PbuildVersion=${{ steps.version.outputs.version }} -x test
