name: Dependency Submission

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  dependencies:
    uses: octopusden/octopus-base/.github/workflows/common-gradle-dependency-submission.yml@9ba0350ce6e0f0897ec3aff105e20c70234b0440
    with:
      java-version: '21'
