name: Gradle Release

on:
  repository_dispatch:
    types: [ release-test ]

jobs:
  build:
    uses: octopusden/octopus-base/.github/workflows/common-java-gradle-release.yml@support-hybrid-flow
    with:
      flow-type: hybrid
      java-version: '11'
    secrets: inherit
