name: Workflow Lint

on:
  push:
    branches: [main]
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  workflow-lint:
    uses: octopusden/octopus-base/.github/workflows/common-workflow-lint.yml@9ba0350ce6e0f0897ec3aff105e20c70234b0440
