name: Workflow Lint

on:
  push:
    branches: [main]
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  workflow-lint:
    uses: octopusden/octopus-base/.github/workflows/common-workflow-lint.yml@v3.1.0
